In [1]:
from gtm import *

# Sample Copulas Package
import pyvinecopulib as pv

# Other Stuff
import numpy as np
import torch
from torch.utils.data import DataLoader
from demos.dataset_helpers import Generic_Dataset

/Users/matthiasherp/anaconda3/envs/pctm/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch

N = 100  # Number of samples
D = 5    # Dimensionality of Gaussian
K = 3    # Number of categories

# 1. Gaussian observations (mean=0, std=1)
y_train = torch.randn(N, D)  # Shape: (N, D)
y_val = torch.randn(N, D)  # Shape: (N, D)

# 2. Categorical identifier variable
x_train = torch.randint(0, K, (N,))  # N integers in {0, 1, ..., K-1}
x_val = torch.randint(0, K, (N,))

In [3]:
from gtm.gtm_layers.transformation_layer import Transformation

t_layer = Transformation(degree=[10] * D,number_variables=D,spline_range=[[-10]*D,[10]*D])

In [4]:
from gtm.gtm_splines.bernstein_prediction_vectorized import binomial_coeffs
device = "cpu"
max_degree = 10
n = max_degree + 1
binom_n = binomial_coeffs(n, device=device)
binom_n1 = binomial_coeffs(n - 1, device=device)
binom_n2 = binomial_coeffs(n - 2, device=device)

from gtm.gtm_layers.transformation_layer import Transformation
# define some params
params = torch.nn.ParameterList(t_layer.compute_starting_values(categories=3))

padded_params = torch.vstack(
            [
                torch.nn.functional.pad(
                    p, (0, max_degree + K - 1 - p.size(0))
                )
                for p in params
            ]
        ).T

# define restriction for params
from gtm.gtm_splines.bernstein_basis import (
    compute_multivariate_bernstein_basis, restrict_parameters)

padded_params_restricted = restrict_parameters(padded_params,covariate=False, degree=10, monotonically_increasing=True)

# import get basis
from gtm.gtm_splines.bernstein_prediction_vectorized import bernstein_basis_batched
from gtm.gtm_splines.splines_utils import ReLULeR

reluler = ReLULeR(torch.FloatTensor([-10,10]))
input_a_clone = reluler.forward(y_train)

n = padded_params_restricted.shape[0] -1 #params_a.shape[0] - 1

# get into the 0,1 range
span_data = 10 - -10 #spline_range[1] - spline_range[0]
input_a_clone = input_a_clone / span_data + 0.5


basis = bernstein_basis_batched(input_a_clone, n, binom=binom_n)  # (N, D, B)

# define get right params
padded_params_restricted_3D = padded_params_restricted.reshape(12,D,K)
cat_dim_idx = x_train
padded_params_restricted_chosen = padded_params_restricted_3D[:,:,cat_dim_idx]

# multiply basis with appropriate params
#torch.matmul(basis, theta.unsqueeze(-1)).squeeze(-1) 
prediction = (basis * padded_params_restricted_chosen.T).sum(2)

/Users/matthiasherp/Desktop/phd_github_repositories/gtm/gtm/gtm_splines/bernstein_prediction_vectorized.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  - torch.lgamma(torch.tensor(n - i + 1.0, device=device))
/var/folders/57/_f_fv4s97k300zslnyj86dxc0000gn/T/ipykernel_35647/1423120164.py:51: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3687.)
  prediction = (basis * padded_params_restricted_chosen.T).sum(2)


In [5]:
padded_params_restricted_3D.size()

torch.Size([12, 5, 3])

In [6]:
padded_params_restricted.size()

torch.Size([12, 15])

In [7]:
basis.size()

torch.Size([100, 5, 12])

In [8]:
prediction.size()

torch.Size([100, 5])

In [9]:
padded_params_restricted_chosen.size()

torch.Size([12, 5, 100])

In [10]:
padded_params_restricted_chosen.T.size()

torch.Size([100, 5, 12])

In [11]:
padded_params_restricted_chosen.T[0,0,:]

tensor([-10.0000,  -8.1818,  -6.3636,  -4.5455,  -2.7273,  -0.9091,   0.9091,
          2.7273,   4.5455,   6.3636,   8.1818,  10.0000],
       grad_fn=<SliceBackward0>)

In [12]:
model = GTM(
    number_variables = D,
    number_transformation_layers = 1,
    number_decorrelation_layers = 0,
    degree_transformations = 10,
    spline_transformation = "bernstein",
    transformation_spline_range = (-10, 10),
    device = "cpu") 

/Users/matthiasherp/Desktop/phd_github_repositories/gtm/gtm/gtm_layers/transformation_layer.py:81: UserWarning: Warning: Varying Spline Degree for each Dimension is not implemented for Bernstein, only for B-Spline.
  warnings.warn(
/Users/matthiasherp/Desktop/phd_github_repositories/gtm/gtm/gtm_layers/transformation_layer.py:90: UserWarning: Bernstein polynomial penalization is not implemented yet. only returns zeros hardcoded in bernstein_prediction.py fct
  warnings.warn(


In [13]:
return_dict = model.transformation(input=y_train)

In [14]:
(return_dict["output"] - prediction).abs().max()

tensor(4.7684e-07, grad_fn=<MaxBackward1>)

In [15]:
from gtm.gtm_splines.bernstein_prediction_vectorized import (
    bernstein_prediction_vectorized, binomial_coeffs)

In [16]:
spline_range = [-10,10]

In [17]:
padded_params_restricted_chosen.size()

torch.Size([12, 5, 100])

In [18]:
y_train.size()

torch.Size([100, 5])

In [19]:
padded_params_restricted_chosen.size()

torch.Size([12, 5, 100])

In [20]:
transformation_spline_range = list(
            [
                [-10] * 5,
                [10] * 5,
            ]
        )

testing version in code:

In [21]:
tm = Transformation(degree=[10] * y_train.size(1),
        number_variables=y_train.size(1),
        spline_range=transformation_spline_range,
        monotonically_increasing=True,
        spline="bernstein",
        span_factor=torch.tensor(0.1),
        number_covariates=False,
        initial_log_transform=False,
        calc_method_bspline="deBoor",
        span_restriction="reluler",
        spline_order=3,
        device="cpu",
        number_of_categories=torch.unique(x_train).size(0)
    )

In [23]:
return_dict = tm.categorical_bernstein_forward(y_train, x_train, log_d=0, inverse=False)

In [24]:
return_dict["output"]

tensor([[ 7.4301e+00, -4.3632e+00, -4.7881e+00,  8.7203e+00,  1.2465e-01],
        [-3.7750e+01, -9.1098e+00,  3.5334e+00, -3.5797e+01, -2.2972e+01],
        [-6.0150e+00,  1.9188e+01,  7.1575e+00,  2.4903e+01, -3.7000e+01],
        [-4.7387e+00, -2.8334e+01, -3.6969e+01, -1.9625e+00, -1.6613e+01],
        [ 9.4325e+00, -2.7000e+01, -3.3000e+01,  2.4514e+01, -2.0276e+01],
        [-1.6997e+01,  2.6650e+01,  7.2192e+00, -2.3572e+01, -3.4109e+01],
        [-1.7466e+01, -9.3481e+00, -5.0664e+00, -5.3444e+00, -3.7500e+01],
        [-2.3644e+01, -5.0472e+00,  2.2235e+01, -1.7246e+01, -5.0868e+00],
        [-2.3622e+01,  8.9871e+00, -9.0438e+00, -8.2804e+00, -1.3993e+01],
        [-2.0722e+01,  5.2000e+01, -2.8651e+01, -1.5713e+01, -4.8323e+00],
        [-3.6078e+01, -3.9000e+01, -1.0173e+01,  1.9105e+01,  2.1272e+01],
        [-3.3602e+01, -1.7235e+01, -4.9393e+00, -1.3352e+00, -1.4482e+00],
        [-3.5828e+01, -1.8773e+01, -4.3506e+00,  1.0802e+01, -1.7474e+01],
        [ 8.5798e+00, -2.

In [25]:
return_dict["log_d"]

tensor([[2.9957, 2.9957, 2.9957, 2.9957, 2.9957],
        [3.3928, 2.9957, 2.9957, 3.0637, 2.9962],
        [2.9957, 2.9957, 2.9957, 2.9957, 3.0995],
        [2.9957, 3.0014, 3.1177, 2.9957, 2.9957],
        [2.9957, 3.9890, 3.6109, 2.9961, 2.9959],
        [2.9958, 2.9957, 2.9957, 2.9966, 3.0367],
        [2.9958, 2.9957, 2.9957, 2.9957, 3.3096],
        [2.9968, 2.9957, 2.9958, 2.9958, 2.9957],
        [2.9968, 2.9957, 2.9957, 2.9957, 2.9957],
        [2.9960, 4.8828, 3.0012, 2.9957, 2.9957],
        [3.0896, 3.1832, 2.9957, 2.9958, 2.9958],
        [3.0303, 2.9958, 2.9957, 2.9957, 2.9957],
        [3.0408, 2.9958, 2.9957, 2.9957, 2.9958],
        [2.9957, 2.9974, 2.9958, 2.9957, 3.0953],
        [2.9957, 2.9957, 2.9957, 2.9957, 3.0137],
        [2.9957, 3.0073, 2.9957, 2.9957, 3.0143],
        [2.9957, 2.9957, 2.9957, 2.9957, 2.9957],
        [2.9957, 2.9957, 2.9957, 2.9963, 2.9957],
        [3.0408, 2.9983, 2.9957, 2.9985, 3.1163],
        [2.9957, 3.0054, 2.9963, 2.9957, 2.9957],
